common: &common
  weibo:
    app_key: "83541187"
    app_secret: "70968cae2cbaf5bf060878d5b169691e"
    redirect_uri: "http://17up.org/members/auth/weibo/callback"
  google:
    app_id: "995938770204.apps.googleusercontent.com"
    app_secret: "SlHYWozODCEj0mWAb1X3qBFS"
    redirect_uri: "http://17up.org/members/auth/google_oauth2/callback"
  twitter:
    app_key: 'jNkSGziKmcUyEVO1Ln8VNw'
    app_secret: 'jHXBVAUuigM0StpxCEISTcGj5l42uz83Ih2NViSia8'
    redirect_uri: "http://17up.org/members/auth/twitter/callback"

production:
  <<: *common

development:
  <<: *common

test:
  <<: *common