common: &common
  weibo:
    app_key: "83541187"
    app_secret: "70968cae2cbaf5bf060878d5b169691e"
    redirect_uri: "http://17up.org/members/auth/weibo/callback"

production:
  <<: *common

development:
  <<: *common

test:
  <<: *common